name: Create draft PR for updated rules
on:
  push:
  repository_dispatch:
    types:
      - set-new-golden
      - set-new-golden-overwrite

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    if: github.event_name == 'repository_dispatch' && github.event.client_payload.event_type == "set-new-golden"
    steps:
      - name: Check out repository code recursively
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Python Packages
        run: |
          pip install firebase-admin
      - name: Execute Python Script
        env:
          CREDS_FILE: ${{ secrets.CREDS_FILE }}
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
        run: python flow/util/updateRules.py --keyFile "${CREDS_FILE}" --apiURL ${API_BASE_URL}
      - name: Push updated rules
        id: remote-update
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          echo "::set-output name=has_update::$(git --no-pager diff --name-only origin/master..HEAD)"
          git add .
          git commit -m "flow: update rules based on new golden reference"
      - if: "steps.remote-update.outputs.has_update != ''"
        name: Create Draft PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ github.token }}
          signoff: true
          delete-branch: true
          title: "[BOT] Update rules"
          reviewers: |
            vvbandeira
            maliberty
          draft: true
          branch: bot-update-rules
          commit-message: |
            [BOT] Update rules
  overwrite:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    if: github.event_name == 'repository_dispatch' && github.event.client_payload.event_type == "set-new-golden-overwrite"
    steps:
      - name: Check out repository code recursively
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Python Packages
        run: |
          pip install firebase-admin
      - name: Execute Python Script
        env:
          CREDS_FILE: ${{ secrets.CREDS_FILE }}
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
        run: python flow/util/updateRules.py --keyFile "${CREDS_FILE}" --apiURL ${API_BASE_URL} --overwrite
      - name: Push updated rules
        id: remote-update
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          echo "::set-output name=has_update::$(git --no-pager diff --name-only origin/master..HEAD)"
          git add .
          git commit -m "flow: update rules based on new golden reference"
      - if: "steps.remote-update.outputs.has_update != ''"
        name: Create Draft PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ github.token }}
          signoff: true
          delete-branch: true
          title: "[BOT] Update rules"
          reviewers: |
            vvbandeira
            maliberty
          draft: true
          branch: bot-update-rules
          commit-message: |
            [BOT] Update rules
